--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.505.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 4/22/2021 5:31:07 PM
-- Server version: 10.5.8
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS assest_traderx;

CREATE DATABASE assest_traderx
	CHARACTER SET latin1
	COLLATE latin1_swedish_ci;

--
-- Set default database
--
USE assest_traderx;

--
-- Create table `account_type`
--
CREATE TABLE account_type (
  account_type_id INT(11) NOT NULL AUTO_INCREMENT,
  account_type VARCHAR(35) NOT NULL,
  PRIMARY KEY (account_type_id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `org_unit`
--
CREATE TABLE org_unit (
  org_unit_id INT(11) NOT NULL AUTO_INCREMENT,
  org_unit_name VARCHAR(35) NOT NULL DEFAULT '',
  credits INT(11) NOT NULL,
  PRIMARY KEY (org_unit_id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create table `user`
--
CREATE TABLE user (
  user_id INT(11) NOT NULL AUTO_INCREMENT,
  username VARCHAR(35) NOT NULL DEFAULT '',
  password VARCHAR(255) NOT NULL DEFAULT '',
  account_type_id INT(11) NOT NULL,
  org_unit_id INT(11) NOT NULL,
  PRIMARY KEY (user_id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `UK_user_username` on table `user`
--
ALTER TABLE user 
  ADD UNIQUE INDEX UK_user_username(username);

--
-- Create foreign key
--
ALTER TABLE user 
  ADD CONSTRAINT FK_user_account_type_account_type_id FOREIGN KEY (account_type_id)
    REFERENCES account_type(account_type_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE user 
  ADD CONSTRAINT FK_user_org_unit_org_unit_id FOREIGN KEY (org_unit_id)
    REFERENCES org_unit(org_unit_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `trade_current`
--
CREATE TABLE trade_current (
  trade_id INT(11) NOT NULL AUTO_INCREMENT,
  trade_type ENUM('BUY','SELL') NOT NULL DEFAULT 'BUY',
  org_unit_id INT(11) NOT NULL,
  org_unit_name VARCHAR(35) NOT NULL,
  user_id INT(11) NOT NULL,
  username VARCHAR(35) NOT NULL DEFAULT '',
  asset_id INT(11) NOT NULL,
  asset_name VARCHAR(35) NOT NULL,
  quantity INT(11) NOT NULL,
  price INT(11) NOT NULL,
  trade_date TIMESTAMP NOT NULL DEFAULT current_timestamp() ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (trade_id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE trade_current 
  ADD CONSTRAINT FK_trade_current_org_unit_org_unit_id FOREIGN KEY (org_unit_id)
    REFERENCES org_unit(org_unit_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `assest`
--
CREATE TABLE assest (
  assest_id INT(11) NOT NULL AUTO_INCREMENT,
  asset_name VARCHAR(35) DEFAULT NULL,
  PRIMARY KEY (assest_id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create index `UK_assest_asset_name` on table `assest`
--
ALTER TABLE assest 
  ADD UNIQUE INDEX UK_assest_asset_name(asset_name);

--
-- Create table `asset_holding`
--
CREATE TABLE asset_holding (
  org_unit_id INT(11) NOT NULL,
  asset_id INT(11) NOT NULL,
  quantity INT(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (org_unit_id, asset_id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

--
-- Create foreign key
--
ALTER TABLE asset_holding 
  ADD CONSTRAINT FK_asset_holding_assest_assest_id FOREIGN KEY (asset_id)
    REFERENCES assest(assest_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE asset_holding 
  ADD CONSTRAINT FK_asset_holding_org_unit_org_unit_id FOREIGN KEY (org_unit_id)
    REFERENCES org_unit(org_unit_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `trade_history`
--
CREATE TABLE trade_history (
  trade_id INT(11) NOT NULL,
  trade_sell INT(11) NOT NULL,
  trade_buy INT(11) NOT NULL,
  trade_type ENUM('BUY','SELL') NOT NULL DEFAULT 'SELL',
  org_unit_name VARCHAR(35) NOT NULL,
  username VARCHAR(35) NOT NULL DEFAULT '',
  asset_name VARCHAR(35) NOT NULL,
  quantity INT(11) NOT NULL,
  price INT(11) NOT NULL,
  trade_date TIMESTAMP NOT NULL DEFAULT current_timestamp() ON UPDATE CURRENT_TIMESTAMP,
  date_processed TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (trade_id)
)
ENGINE = INNODB,
CHARACTER SET latin1,
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table account_type
--
-- Table assest_traderx.account_type does not contain any data (it is empty)

-- 
-- Dumping data for table org_unit
--
-- Table assest_traderx.org_unit does not contain any data (it is empty)

-- 
-- Dumping data for table assest
--
-- Table assest_traderx.assest does not contain any data (it is empty)

-- 
-- Dumping data for table user
--
-- Table assest_traderx.user does not contain any data (it is empty)

-- 
-- Dumping data for table trade_history
--
-- Table assest_traderx.trade_history does not contain any data (it is empty)

-- 
-- Dumping data for table trade_current
--
-- Table assest_traderx.trade_current does not contain any data (it is empty)

-- 
-- Dumping data for table asset_holding
--
-- Table assest_traderx.asset_holding does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;