package AssetTradingPlatform.common;

/**
 * Asset Creation
 */
public class Asset {
    /**
     * Autogenerated incremental ID of asset upon successful creation
     */
    public int asset_id;
    /**
     * Asset Name
     */
    public String asset_name;

    /**
     * Create and save a new Asset
     *
     * @param asset_name New assets name
     */
    public Asset(String asset_name) {
        /**
         * "Add Asset" btn, will bring up a dialog box, with a txt input.
         *  Once confirmed it is added to the DB.
         */
        
    }
}
