package AssetTradingPlatform.common;

/**
 * Asset Creation
 */
public class Asset {
    /**
     * Autogenerated incremental ID of Asset upon successful creation
     */
    public int asset_id;
    public String asset_name = null;


    /**
     * Create a new Asset
     * A new asset is created and saved to collection of existing assets
     * @param asset_name New assets name
     */
    public Asset(String asset_name){
    }
}
