package AssetTradingPlatform.common;

/**
 * Asset Creation
 */
public class Asset {
    /**
     * Autogenerated incremental ID of asset upon successful creation
     */
    private int asset_id;
    /**
     * Asset Name
     */
    private String asset_name;

    //Temporary id counter to increment
    private int counter_id = 0;

    /**
     * Create and save a new Asset
     *
     * @param name New assets name
     */
    public Asset(String name) {
        asset_name = name;
        asset_id = counter_id + 1;
        counter_id += 1;
        /**
         * "Add Asset" btn, will bring up a dialog box, with a txt input.
         *  Once confirmed it is added to the DB.
         */
        
    }
}
