--
-- Script was generated by Devart dbForge Studio 2020 for MySQL
-- Product home page:
-- Script date
-- Server version:
-- Client version:
--

-- **** Very IMPORTANT ****
-- Check and change following statements
-- 1) DROP DATABASE IF EXISTS <database name>
-- 2) CREATE DATABASE <database name>
-- 3) USE <database name>;

--
-- Disable foreign keys
--
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

--
-- Set SQL mode
--
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

--
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS asset_trader;

CREATE DATABASE asset_trader
CHARACTER SET utf8
COLLATE utf8_general_ci;

--
-- Set default database
--
USE asset_trader;

--
-- Create table `asset`
--
CREATE TABLE asset (
  asset_id int(11) NOT NULL AUTO_INCREMENT,
  asset_name varchar(35) DEFAULT NULL,
  PRIMARY KEY (asset_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `account_type`
--
CREATE TABLE account_type (
  account_type_id int(11) NOT NULL AUTO_INCREMENT,
  account_type varchar(15) NOT NULL,
  PRIMARY KEY (account_type_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `org_unit`
--
CREATE TABLE org_unit (
  org_unit_id int(11) NOT NULL AUTO_INCREMENT,
  org_unit_name varchar(35) NOT NULL,
  credits int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (org_unit_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 14,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `user`
--
CREATE TABLE user (
  user_id int(11) NOT NULL AUTO_INCREMENT,
  username varchar(35) NOT NULL,
  password varchar(255) NOT NULL,
  account_type_id int(11) NOT NULL,
  org_unit_id int(11) NOT NULL,
  PRIMARY KEY (user_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `UK_user_username` on table `user`
--
ALTER TABLE user
ADD UNIQUE INDEX UK_user_username (username);

--
-- Create foreign key
--
ALTER TABLE user
ADD CONSTRAINT FK_user_account_type_account_type_id FOREIGN KEY (account_type_id)
REFERENCES account_type (account_type_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE user
ADD CONSTRAINT FK_user_org_unit_org_unit_id FOREIGN KEY (org_unit_id)
REFERENCES org_unit (org_unit_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `trade_current`
--
CREATE TABLE trade_current (
  trade_id int(11) NOT NULL AUTO_INCREMENT,
  trade_type enum ('BUY', 'SELL') NOT NULL DEFAULT 'BUY',
  org_unit_id int(11) NOT NULL,
  org_unit_name varchar(35) NOT NULL,
  user_id int(11) NOT NULL,
  username varchar(35) NOT NULL,
  asset_id int(11) NOT NULL,
  asset_name varchar(35) NOT NULL,
  quantity smallint(6) NOT NULL DEFAULT 0,
  price int(11) NOT NULL DEFAULT 0,
  trade_date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (trade_id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE trade_current
ADD CONSTRAINT FK_trade_current_org_unit_org_unit_id FOREIGN KEY (org_unit_id)
REFERENCES org_unit (org_unit_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `asset_holding`
--
CREATE TABLE asset_holding (
  org_unit_id int(11) NOT NULL,
  asset_id int(11) NOT NULL,
  quantity int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (org_unit_id, asset_id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE asset_holding
ADD CONSTRAINT FK_asset_holding_asset_asset_id FOREIGN KEY (asset_id)
REFERENCES asset (asset_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE asset_holding
ADD CONSTRAINT FK_asset_holding_org_unit_org_unit_id FOREIGN KEY (org_unit_id)
REFERENCES org_unit (org_unit_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

--
-- Create table `trade_history`
--
CREATE TABLE trade_history (
  trade_id_sell int(11) NOT NULL,
  trade_id_buy int(11) NOT NULL,
  trade_type enum ('BUY', 'SELL') DEFAULT NULL,
  org_unit_name varchar(35) DEFAULT NULL,
  username varchar(35) DEFAULT NULL,
  asset_name varchar(35) DEFAULT NULL,
  quantity smallint(6) DEFAULT 0,
  price int(11) DEFAULT 0,
  trade_date timestamp NULL DEFAULT NULL,
  date_processed timestamp NULL DEFAULT NULL
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create index `UK_trade_history` on table `trade_history`
--
ALTER TABLE trade_history
ADD UNIQUE INDEX UK_trade_history (trade_id_sell, trade_id_buy, trade_type);


DELIMITER $$
--
-- Create procedure `sp_process_trade_request`
--

--
-- Create procedure `sp_process_asset_sale`
--


DELIMITER ;

--
-- Restore previous SQL mode
--
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

--
-- Enable foreign keys
--
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;